# Generated by Django 5.2.5 on 2025-10-29 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extractions', '0002_rename_duration_prescription_doctor_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prescription',
            name='medicines',
        ),
        migrations.AddField(
            model_name='prescription',
            name='age',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='prescription',
            name='duration',
            field=models.CharField(default='N/A', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='prescription',
            name='frequency',
            field=models.CharField(default='N/A', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='prescription',
            name='medicine_name',
            field=models.CharField(default='N/A', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='prescription',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='diagnosis',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='dosage',
            field=models.CharField(max_length=100),
        ),
    ]
