# Generated by Django 5.2.5 on 2025-10-31 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extractions', '0003_remove_prescription_medicines_prescription_age_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientCaseStudy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=15)),
                ('food_allergy', models.BooleanField(default=False)),
                ('heart_disease', models.BooleanField(default=False)),
                ('diabetic', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
