# Generated by Django 5.2.5 on 2025-10-31 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extractions', '0005_casestudy_delete_patientcasestudy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='age',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
