# Generated by Django 5.2.5 on 2025-11-01 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extractions', '0006_alter_patient_age'),
    ]

    operations = [
        migrations.CreateModel(
            name='DoctorSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doctor_name', models.CharField(max_length=100)),
                ('weekday', models.CharField(max_length=20)),
                ('visiting_time', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], max_length=10)),
            ],
        ),
    ]
