# Generated by Django 5.2.5 on 2025-11-01 06:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extractions', '0007_doctorschedule'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='department',
            name='description',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='contact',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='specialty',
        ),
        migrations.AddField(
            model_name='doctor',
            name='department',
            field=models.ForeignKey(default='exit', on_delete=django.db.models.deletion.CASCADE, to='extractions.department'),
            preserve_default=False,
        ),
    ]
