# Generated by Django 5.2.5 on 2025-11-01 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extractions', '0008_remove_department_description_remove_doctor_contact_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='status',
            field=models.CharField(choices=[('admitted', 'Admitted'), ('discharged', 'Discharged'), ('under_treatment', 'Under Treatment')], default='under_treatment', max_length=20),
        ),
        migrations.AlterField(
            model_name='patient',
            name='age',
            field=models.CharField(default='active', max_length=20),
            preserve_default=False,
        ),
    ]
