# Generated by Django 5.2.5 on 2025-11-01 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extractions', '0009_patient_status_alter_patient_age'),
    ]

    operations = [
        migrations.CreateModel(
            name='DischargedPatient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('age', models.IntegerField()),
                ('gender', models.CharField(max_length=10)),
                ('contact', models.CharField(blank=True, max_length=15, null=True)),
                ('medical_history', models.TextField(blank=True, null=True)),
                ('allergies', models.TextField(blank=True, null=True)),
                ('medications', models.TextField(blank=True, null=True)),
                ('discharged_on', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='patient',
            name='status',
            field=models.CharField(choices=[('admitted', 'Admitted'), ('under_treatment', 'Under Treatment'), ('discharged', 'Discharged')], default='under_treatment', max_length=20),
        ),
    ]
