# Generated by Django 5.2.5 on 2025-11-01 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extractions', '0011_delete_dischargedpatient_department_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='department',
        ),
        migrations.AlterField(
            model_name='doctor',
            name='specialty',
            field=models.CharField(default='exit', max_length=100),
            preserve_default=False,
        ),
    ]
