# Generated by Django 5.2.5 on 2025-11-01 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extractions', '0012_remove_doctor_department_alter_doctor_specialty'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='date',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='status',
        ),
        migrations.AlterField(
            model_name='patient',
            name='age',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
