# Generated by Django 5.2.5 on 2025-11-01 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extractions', '0013_remove_patient_date_remove_patient_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('existing', 'Existing'), ('discharged', 'Discharged')], default='new', max_length=20),
        ),
    ]
