# Generated by Django 5.2.5 on 2025-11-01 07:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('extractions', '0014_patient_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='status',
        ),
    ]
