# Generated by Django 5.2.5 on 2025-11-01 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extractions', '0015_remove_patient_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='age',
            field=models.CharField(default='exit', max_length=10),
            preserve_default=False,
        ),
    ]
