# Generated by Django 5.2.5 on 2025-11-01 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extractions', '0016_alter_patient_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='age',
            field=models.IntegerField(),
        ),
    ]
